# Use the PHP 7.3 runtime by replacing "php72" below with "php73"
runtime: php73

# Defaults to "serve index.php" 
# entrypoint: serve index.php

# If your main page is index.php, comment the above entrypoint setting 


# Use        gcloud app deploy        to deploy to GCP

# https://cs4750db-268423.appspot.com/